/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "copyrightText": "©2012 John Einselen, Vectorform LLC",
    "done": "done",
    "download": "download",
    "drop": "drop image files here",
    "dropDetail": "PNG or TIFF files are ideal",
    "fail": "file processing failed\nplease try again",
    "iaian7com": "For more, visit\niaian7.com/dashboard/sheets",
    "locationText": "ImageMagick",
    "nameFileText": "file sheet prefix",
    "nameSpriteText": "sprite suffix",
    "nameText": "sprite sheet suffix",
    "namingText": "file naming",
    "new": "new update available!",
    "newVersion": "version number\nversion description",
    "outputText": "output files",
    "scaleText": "resize algorithm",
    "skip": "skip version",
    "success": "file processing successful, busy creating sheets",
    "successDetails": "depending on image size\nthis could take a minute",
    "wrong": "wrong file format\nplease try again"
};









