/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "doneSave": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showFront", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "download": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "versionDownload", "rightImageWidth": 5, "text": "download", "view": "DC.View" },
    "drop": { "text": "drop", "view": "DC.Text" },
    "failButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "failText": { "text": "fail", "view": "DC.Text" },
    "iaian7com": { "text": "iaian7com", "view": "DC.Text" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack", "view": "DC.View" },
    "locationText": { "text": "locationText", "view": "DC.Text" },
    "nameFileText": { "text": "nameFileText", "view": "DC.Text" },
    "nameSpriteText": { "text": "nameSpriteText", "view": "DC.Text" },
    "new": { "text": "new", "view": "DC.Text" },
    "newVersion": { "text": "newVersion", "view": "DC.Text" },
    "output": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "name": "output", "onchange": "updateOutput", "options": [["alpha on", "0"], ["alpha off", "1"], ["alpha extract", "2"], ["multiple files", "3"]], "rightImageWidth": 16, "view": "DC.View" },
    "outputText": { "text": "outputText", "view": "DC.Text" },
    "scale": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "name": "scale", "onchange": "updateScale", "options": [["point", "Point"], ["box", "Box"], ["cubic", "Cubic"], ["quadratic", "Quadratic", true], ["gaussian", "Gaussian"], ["mitchell", "Mitchell"], ["catrom", "Catrom"], ["lanczos", "Lanczos"]], "rightImageWidth": 16, "view": "DC.View" },
    "scaleText": { "text": "scaleText", "view": "DC.Text" },
    "skip": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "skip", "view": "DC.View" },
    "stack": { "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }], "view": "DC.StackLayout" },
    "successButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "successDetails": { "text": "successDetails", "view": "DC.Text" },
    "successText": { "text": "success", "view": "DC.Text" },
    "text": { "text": "copyrightText", "view": "DC.Text" },
    "type": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "name": "type", "onchange": "updateType", "options": [["auto sprite sheet", "square"], ["horizontal strip", "stripH"], ["vertical strip", "stripV"], ["custom resize", "resize"], ["custom tile", "tile"], ["custom resize+tile", "custom"], ["auto file sheet", "file"]], "rightImageWidth": 16, "view": "DC.View" },
    "wrongButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "wrongText": { "text": "wrong", "view": "DC.Text" }
};



