/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "copyrightText": "©2009 John Einselen / Vectorform LLC",
    "done": "done",
    "download": "download",
    "drop": "drop PNG files here",
    "fail": "file processing failed\nplease try again",
    "iaian7com": "For more information, please visit iaian7.com/dashboard/sheets",
    "locationText": "ImageMagick install location",
    "nameFileText": "file sheet prefix",
    "nameSpriteText": "sprite sheet suffix",
    "nameText": "sprite sheet suffix",
    "nameText2": "file sheet prefix",
    "new": "new update available!",
    "newVersion": "version number\nversion description",
    "skip": "skip version",
    "success": "file processing successful, busy creating sheets",
    "successDetails": "depending on image size\nthis could take a minute",
    "wrong": "wrong file format\nplease try again"
};

