/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "customText": "Custom image name",
    "done": "done",
    "download": "download",
    "drop": "drop PNG files here",
    "explanation": "(leave blank for auto naming of output file)",
    "fail": "file conversion failed\nplease try again",
    "iaian7com": "For more information, please visit iaian7.com/dashboard/sheets",
    "new": "new update available!",
    "newVersion": "version number\nversion description",
    "preset1": "ImageMagick Montage install location",
    "preset2": "user preset 2",
    "skip": "skip version",
    "success": "file conversion\nwas successful",
    "success2": "(envelope files saved)",
    "successAE": "file conversion\nwas successful\n(and copied to clipboard)",
    "successAE2": "sequential phoneme list:",
    "successAEoutput": "sequential phoneme list",
    "wrong": "wrong file format\nplease try again"
};
